CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    ENABLED INTEGER NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    DEPT VARCHAR(35) NOT NULL,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE USER_ROLES (
    USER_ROLE_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    AUTHORITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT FK_USER_ROLES FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

create table USER_ACCESS_AUDIT(
    USER_ID varchar(45) not null,
    DATE_TIME TIMESTAMP not null,
    ACTION_TYPE varchar(50) not null,
    SESSION_ID varchar(80) not null,
    REMARK varchar(100) null
);
